### ISSUE TITLE
IllegalPluginAccessException when disabling plugin

### ISSUE THREAD

**Issue by TypicalFin** [Ordwen/ODailyQuests#1]
Server version: 1.19
Plugin version: 1.3.4-beta
Using MySQL.

```[07:19:18 INFO]: [O'DailyQuests] Disabling ODailyQuests v1.3.4-beta-SNAPSHOT
[07:19:18 ERROR]: Error occurred while disabling ODailyQuests v1.3.4-beta-SNAPSHOT (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[purpur-1.19.jar:git-Purpur-1708]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:251) ~[purpur-1.19.jar:git-Purpur-1708]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[purpur-1.19.jar:git-Purpur-1708]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:192) ~[purpur-1.19.jar:git-Purpur-1708]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:161) ~[purpur-1.19.jar:git-Purpur-1708]
        at com.ordwen.odailyquests.quests.player.progression.storage.mysql.SaveProgressionSQL.saveProgression(SaveProgressionSQL.java:51) ~[ODailyQuests-1.3.4-beta.jar:?]
        at com.ordwen.odailyquests.ODailyQuests.onDisable(ODailyQuests.java:170) ~[ODailyQuests-1.3.4-beta.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:556) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:528) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:942) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:820) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.19.jar:git-Purpur-1708]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1708]```

**Comment by Ordwen** [comment]
Hello !

Thank you for pointing out this error.
I will try to reproduce this and fix it in the next update.

**Comment by TypicalFin** [comment]
Thanks! It only seems to happen when you are using MySQL, when saving to the file it works perfectly.

**Comment by Ordwen** [comment]
Hello!
Sorry it took me so long to fix this problem, but here it is! 

Thanks again for pointing it out :)

**Comment by Ordwen** [comment]
Wow, I definitely don't handle GitHub very well...
Here is the download link : https://github.com/Ordwen/ODailyQuests/releases/tag/v1.3.5-beta-SNAPSHOT
