### ISSUE TITLE
MySQL connection leak without table dailyquests.player

### ISSUE THREAD

**Issue by ghost** [Ordwen/ODailyQuests#31]
Hi I am using MySQL to drive the plugin. But when I set all things up and make sure nothing configures for wrong I found this when joining

[17:09:13 ERROR]: [O'DailyQuests] An error occurred while loading player XXXXXX quests progression.
[17:09:13 WARN]: java.sql.SQLSyntaxErrorException: Table 'dailyquests.player' doesn't exist
[17:09:13 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[17:09:13 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[17:09:13 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[17:09:13 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
[17:09:13 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[17:09:13 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[17:09:13 WARN]:        at ODailyQuests-2.2.3.jar//com.ordwen.odailyquests.quests.player.progression.storage.sql.LoadProgressionSQL.lambda$loadProgression$0(LoadProgressionSQL.java:61)
[17:09:13 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:09:13 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:09:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:09:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:09:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:09:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

[17:09:23 WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@654bf2c7 on thread Craft Scheduler Thread - 29 - ODailyQuests, stack trace follows
java.lang.Exception: Apparent connection leak detected
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[?:?]
        at com.ordwen.odailyquests.quests.player.progression.storage.sql.SQLManager.getConnection(SQLManager.java:91) ~[ODailyQuests-2.2.3.jar:?]
        at com.ordwen.odailyquests.quests.player.progression.storage.sql.LoadProgressionSQL.lambda$loadProgression$0(LoadProgressionSQL.java:57) ~[ODailyQuests-2.2.3.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[divinemc-1.19.4.jar:git-DivineMC-"baace97"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[divinemc-1.19.4.jar:git-DivineMC-"baace97"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[divinemc-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Ordwen** [comment]
Hello,

It's strange, the table should be created automatically. 
Can you send me a full logs file to see if something else is happening please?


On which database management system is running the database? (MySQL, MariaDB, PostgreSQL, Oracle...)
Is the table PROGRESSION created or not?
Finally, can send me a screenshot of all tables of your database please?

Are you able to create it manually? Directly from phpMyAdmin if you have access, or from console with the commands :

```SQL
create table PLAYER (
   PLAYERNAME char(32)  not null,
   PLAYERTIMESTAMP bigint not null,
   ACHIEVEDQUESTS tinyint not null,
   TOTALACHIEVEDQUESTS int not null,
   constraint PK_PLAYER primary key (PLAYERNAME)
);                    
```

Thank you.

**Comment by TheNoobestPlayer** [comment]
OK sure. I'll provide some information first. Server version 1.19.4. Using MySQL 8.0.36. The plugin works fine at enable/disable process. Only when player joined server the problem happens. The only error message is listed above. And there's only "progression" table on the database. After I ran the command above and rejoin the error disappeared.

**Comment by TheNoobestPlayer** [comment]
Sure oky I am pretty sure it does since when I create the table, do complete command and shutdown the server I can see the data were saved into the tables so the records had been successfully created. As for extra message I ll build a separate testing server and try again. It won't be long but I can't do it now maybe. And should be tomorrow I can offer you a completely log without other plugins :］

**Comment by TheNoobestPlayer** [comment]
Something changes my schedule. I'll offer you the log now
https://pastebin.com/HASXGHU7

**Comment by TheNoobestPlayer** [comment]
Here is the log after I ran SQL command to create the player table. Everything is fine now without errors.
https://pastebin.com/uRigfc6A

**Comment by Ordwen** [comment]
> Something changes my schedule. I'll offer you the log now https://pastebin.com/HASXGHU7
Thank you. I don't understand, looks like the plugin is just skipping the creation of the PLAYER table...

**Comment by TheNoobestPlayer** [comment]
Ahhh maybe it's the server core's problem? I ll now try to use Paper to test again.

**Comment by TheNoobestPlayer** [comment]
Yes I used latest Paper build but got the same problem. So, it's basically caused by something inside the plugin itself.

**Comment by Ordwen** [comment]
> Yes I used latest Paper build but got the same problem. So, it's basically caused by something inside the plugin itself.

This is the first time someone has reported this problem to me. And that doesn't make sense, I don't understand why the PROGRESSION table is created but not the PLAYER table, it doesn't even appear in the logs even though it's exactly the same process...

I will send you a debug version soon with additional logs to try to understand what is happening

**Comment by Ordwen** [comment]
Fixed in 3.0
https://github.com/Ordwen/ODailyQuests/releases/tag/nightly-3.0.0
