### ISSUE TITLE
Could not pass event EntityDeathEvent to ODailyQuests v2.2.5

### ISSUE THREAD

**Issue by M3rcena** [Ordwen/ODailyQuests#53]
[21:43:42 ERROR]: Could not pass event EntityDeathEvent to ODailyQuests v2.2.5
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "com.ordwen.odailyquests.configuration.functionalities.progression.ProgressionMessage.message" is null
        at com.ordwen.odailyquests.configuration.functionalities.progression.ProgressionMessage.sendProgressionMessage(ProgressionMessage.java:68) ~[ODailyQuests-2.2.5.jar:?]
        at com.ordwen.odailyquests.quests.player.progression.QuestProgressUtils.runProgress(QuestProgressUtils.java:78) ~[ODailyQuests-2.2.5.jar:?]
        at com.ordwen.odailyquests.quests.player.progression.QuestProgressUtils.actionQuest(QuestProgressUtils.java:33) ~[ODailyQuests-2.2.5.jar:?]
        at com.ordwen.odailyquests.quests.player.progression.checkers.AbstractEntityChecker.setPlayerQuestProgression(AbstractEntityChecker.java:81) ~[ODailyQuests-2.2.5.jar:?]
        at com.ordwen.odailyquests.events.listeners.entity.EntityDeathListener.onEntityDeathEvent(EntityDeathListener.java:37) ~[ODailyQuests-2.2.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1300.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[?:git-UniverseSpigot-"16550e8"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[?:git-UniverseSpigot-"16550e8"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:git-UniverseSpigot-"16550e8"]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:76) ~[?:git-UniverseSpigot-"16550e8"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[?:git-UniverseSpigot-"16550e8"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[?:git-UniverseSpigot-"16550e8"]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:987) ~[?:git-UniverseSpigot-"16550e8"]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1901) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1875) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1792) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1602) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:321) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1357) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2351) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2803) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2727) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:git-UniverseSpigot-"16550e8"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1474) ~[?:git-UniverseSpigot-"16550e8"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:196) ~[?:git-UniverseSpigot-"16550e8"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1451) ~[?:git-UniverseSpigot-"16550e8"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1379) ~[?:git-UniverseSpigot-"16550e8"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1357) ~[?:git-UniverseSpigot-"16550e8"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[?:git-UniverseSpigot-"16550e8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[?:git-UniverseSpigot-"16550e8"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Ordwen** [comment]
Delete your config.yml and let the plugin regenerate it, it's missing some options. Are you using a config you downloaded somewhere?

**Comment by M3rcena** [comment]
> Delete your config.yml and let the plugin regenerate it, it's missing some options. Are you using a config you downloaded somewhere?

Yeah, it was custom config.yml 

I deleted it and restarted the server. It seems to work, thanks
