### ISSUE TITLE
SPRUCE_WALL_SIGN is not an item

### ISSUE THREAD

**Issue by BurkenDev** [Ordwen/ODailyQuests#55]
[09:33:31] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to ODailyQuests v2.2.5
java.lang.IllegalArgumentException: SPRUCE_WALL_SIGN isn't an item
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.events.listeners.item.BlockPlaceListener.onBlockPlaceEvent(BlockPlaceListener.java:48) ~[ODailyQuests-2.2.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor683.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-44-8d91b85]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-44-8d91b85]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:449) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:487) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:607) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1871) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1541) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1518) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1511) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1470) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1477) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1322) ~[paper-1.21.jar:1.21-44-8d91b85]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-44-8d91b85]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Ordwen** [comment]
Hello, it is related to the 1.21. It is fixed in [this snapshot](https://github.com/Ordwen/ODailyQuests/releases/download/SNAPSHOT/ODailyQuests-2.3.0-SNAPSHOT-7.jar).

**Comment by uouiiu** [comment]
The server version is 1.21 purpur.  itemsadder version is v4.0.2-alpha-test-3
