### ISSUE TITLE
After using the itemsadder icon for the task icon, reloading the plugin gives an error and it doesn't work!

### ISSUE THREAD

**Issue by uouiiu** [Ordwen/ODailyQuests#59]
org.bukkit.command.CommandException: Unhandled exception executing command 'qadmin' in plugin ODailyQuests v2.2.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.jar:1.21-2280-930003b]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast ia.m.eH to org.bukkit.craftbukkit.inventory.CraftItemStack
	at java.base/java.lang.Class.cast(Class.java:4067) ~[?:?]
	at org.bukkit.craftbukkit.inventory.CraftItemStack.getCraftStack(CraftItemStack.java:46) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:97) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[purpur-1.21.jar:1.21-2280-930003b]
	at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.interfaces.QuestsInterfaces.loadSelectedInterface(QuestsInterfaces.java:126) ~[ODailyQuests-2.2.5.jar:?]
	at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.interfaces.QuestsInterfaces.loadGlobalInterface(QuestsInterfaces.java:55) ~[ODailyQuests-2.2.5.jar:?]
	at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.interfaces.InterfacesManager.loadQuestsInterfaces(InterfacesManager.java:85) ~[ODailyQuests-2.2.5.jar:?]
	at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.interfaces.InterfacesManager.loadInterfaces(InterfacesManager.java:62) ~[ODailyQuests-2.2.5.jar:?]
	at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.interfaces.InterfacesManager.initAllObjects(InterfacesManager.java:54) ~[ODailyQuests-2.2.5.jar:?]
	at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.admin.ReloadService.reload(ReloadService.java:128) ~[ODailyQuests-2.2.5.jar:?]
	at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.admin.AdminCommands.onCommand(AdminCommands.java:28) ~[ODailyQuests-2.2.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	... 27 more

**Comment by uouiiu** [comment]
The server version is 1.21 purpur.

**Comment by Ordwen** [comment]
Hello, can you please send me the complete log file to see if there is another error?
Also, is this your review?

![image](https://github.com/user-attachments/assets/d545e962-af15-4d9e-b09e-f01f1d0194b1)

**Comment by uouiiu** [comment]
[latest.log](https://github.com/user-attachments/files/16532803/latest.log)
That was my comment, no matter how I try to get it to work it doesn't work, setting it wrong suggests that itemsadder doesn't have the item, setting it right reloads the plugin and it crashes and doesn't work!

**Comment by Ordwen** [comment]
Okay, so in the scheme of things the first thing to do was to create this GitHub issue. 
But that's okay, I'll try to help you and I hope you'll change your rating when your problem is fixed.

First of all, regarding the error you sent me above, it's unknown to me and at first sight it comes from a bad conversion of an item coming from ItemsAdder. I also see errors coming directly from ItemsAdder, but I don't think the problem is related.

I suspect that the ItemsAdder API has changed for V4, so I need to find out what these changes are and how to implement them in ODailyQuests. I also need to get the plugin (because I don't have it and I don't intend to pay 19€) and the developer never got back to me... If you could please send me your version, it would be a great help.

To try to reproduce the problem on my side, I would need the following items: 
- your ODailyQuests folder
- your ItemsAdder folder
- your version of ItemsAdder

You can put everything in a .zip archive, it'll be easier. Thank you for your help.

**Comment by Ordwen** [comment]
> [latest.log](https://github.com/user-attachments/files/16532803/latest.log) That was my comment, no matter how I try to get it to work it doesn't work, setting it wrong suggests that itemsadder doesn't have the item, setting it right reloads the plugin and it crashes and doesn't work!

Hello,

You've given my plugin a bad rating for an error that apparently stems from an ItemsAdder update and is therefore not directly my responsibility. I'd like to help you, but now I need the items I've listed above, otherwise I can't do anything... At least think of the other users please...

**Comment by Ordwen** [comment]
> org.bukkit.command.CommandException: Unhandled exception executing command 'qadmin' in plugin ODailyQuests v2.2.5 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.jar:1.21-2280-930003b] at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?] at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354) ~[purpur-1.21.jar:1.21-2280-930003b] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] Caused by: java.lang.ClassCastException: Cannot cast ia.m.eH to org.bukkit.craftbukkit.inventory.CraftItemStack at java.base/java.lang.Class.cast(Class.java:4067) ~[?:?] at org.bukkit.craftbukkit.inventory.CraftItemStack.getCraftStack(CraftItemStack.java:46) ~[purpur-1.21.jar:1.21-2280-930003b] at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:97) ~[purpur-1.21.jar:1.21-2280-930003b] at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[purpur-1.21.jar:1.21-2280-930003b] at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.interfaces.QuestsInterfaces.loadSelectedInterface(QuestsInterfaces.java:126) ~[ODailyQuests-2.2.5.jar:?] at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.interfaces.QuestsInterfaces.loadGlobalInterface(QuestsInterfaces.java:55) ~[ODailyQuests-2.2.5.jar:?] at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.interfaces.InterfacesManager.loadQuestsInterfaces(InterfacesManager.java:85) ~[ODailyQuests-2.2.5.jar:?] at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.interfaces.InterfacesManager.loadInterfaces(InterfacesManager.java:62) ~[ODailyQuests-2.2.5.jar:?] at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.interfaces.InterfacesManager.initAllObjects(InterfacesManager.java:54) ~[ODailyQuests-2.2.5.jar:?] at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.admin.ReloadService.reload(ReloadService.java:128) ~[ODailyQuests-2.2.5.jar:?] at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.commands.admin.AdminCommands.onCommand(AdminCommands.java:28) ~[ODailyQuests-2.2.5.jar:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?] ... 27 more

Hello,

Just to let you know that this is a known issue from the ItemsAdder API ([here is the linked issue](https://github.com/PluginBugs/Issues-ItemsAdder/issues/3825)).

[Here's a snapshot](https://github.com/Ordwen/ODailyQuests/releases/download/2.3.0-SNAPSHOT/ODailyQuests-2.3.0-SNAPSHOT-14.jar) of ODailyQuests where the problem is temporary fixed.

Regards.
