### ISSUE TITLE
ODailyQuests

### ISSUE THREAD

**Issue by Noooler** [Ordwen/ODailyQuests#68]
[20:41:41 ERROR]: Could not pass event EntityDeathEvent to ODailyQuests v2.2.5
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "com.ordwen.odailyquests.configuration.functionalities.progression.ProgressionMessage.message" is null
        at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.configuration.functionalities.progression.ProgressionMessage.sendProgressionMessage(ProgressionMessage.java:68) ~[ODailyQuests-2.2.5.jar:?]
        at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.quests.player.progression.QuestProgressUtils.runProgress(QuestProgressUtils.java:78) ~[ODailyQuests-2.2.5.jar:?]
        at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.quests.player.progression.QuestProgressUtils.actionQuest(QuestProgressUtils.java:33) ~[ODailyQuests-2.2.5.jar:?]
        at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.quests.player.progression.checkers.AbstractEntityChecker.setPlayerQuestProgression(AbstractEntityChecker.java:81) ~[ODailyQuests-2.2.5.jar:?]
        at ODailyQuests-2.2.5.jar/com.ordwen.odailyquests.events.listeners.entity.EntityDeathListener.onEntityDeathEvent(EntityDeathListener.java:37) ~[ODailyQuests-2.2.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1584.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-131-84281ce]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:998) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1878) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1781) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1586) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1344) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2420) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2879) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2790) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Ordwen** [comment]
You're using an outdated configuration. Delete your config.yml file and let the plugin regenerate it. Also, use the latest snapshot available [here](https://github.com/Ordwen/ODailyQuests/releases/tag/2.3.0-SNAPSHOT).
